#!/bin/bash

SYMLINKS=".bash_profile .bashrc .bash_profile.d .bashrc.d .aliases.d"

test() {
    create_symlinks
    echo -en "\033[0;31m"
    cat <<EOF

===============================
== ENTERING TEST ENVIRONMENT ==
===============================

EOF
    echo -en "\033[0;0m"
    env -i \
        TERM=xterm \
        HOME=$HOME \
    /bin/bash --rcfile .bash_profile
    echo -en "\033[0;32m"
    cat <<EOF

==============================
== LEAVING TEST ENVIRONMENT ==
==============================

EOF
    echo -en "\033[0;0m"
}

create_symlinks() {
    for symlink in $SYMLINKS; do
        target=${symlink:1}
        [ ! -L $symlink ] && [ -e $target ] && ln -s $target $symlink
    done
}

delete_symlinks() {
    for symlink in $SYMLINKS; do
        [ -L $symlink ] && rm $symlink
    done
}

if [ -n "$1" ]; then
    $1
else
    test
fi